// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

library BaseErrors {

    uint16 constant SENDER__ONLY_SENDER__ERROR = 1001;
    uint16 constant SENDER__ONLY_OWNER_OR_SENDER__ERROR = 1002;
    uint16 constant SENDER__SENDER_NOT_EXISTS__ERROR = 1003;

    uint16 constant WITHDRAWAL__TARGET_ADDRESS_IS_CONTRACT__ERROR = 1101;
    uint16 constant WITHDRAWAL__COINS_BALANCE_NOT_ENOUGH__ERROR = 1102;
    uint16 constant WITHDRAWAL__TRANSFER_FAILED__ERROR = 1103;
    uint16 constant WITHDRAWAL__TOKENS_BALANCE_NOT_ENOUGH__ERROR = 1104;

    uint16 constant MASSPAYOUT__ADDRESS_IS_NOT_CONTRACT__ERROR = 1201;
    uint16 constant MASSPAYOUT__TOKEN_NOT_FOUND__ERROR = 1202;
    uint16 constant MASSPAYOUT__TOKEN_NOT_SUPPORTED__ERROR = 1203;
    uint16 constant MASSPAYOUT__WRONG_LIST_PARAMS_COUNT__ERROR = 1204;
    uint16 constant MASSPAYOUT__TOKEN_ALLOWANCE_NOT_ENOUGH__ERROR = 1205;
    uint16 constant MASSPAYOUT__MASSPAYOUT_EXECUTED_ALREADY__ERROR = 1206;
}
